parameter_defaults:
   management_provider_network: VIO-FLOATING
   cik: xxx

resource_registry:
   "packetlogic::channel_networks::channel":    http://172.21.6.152/sandvine/channel_networks_ns/channel.yaml
   "packetlogic::channel_networks::ns":    http://172.21.6.152/sandvine/channel_networks_ns/nsd.yaml
   "packetlogic::contrail_networks::channel":    http://172.21.6.152/sandvine/contrail_networks_ns/contrail_channel.yaml
   "packetlogic::contrail_networks::ns":    http://172.21.6.152/sandvine/contrail_networks_ns/nsd.yaml
   "packetlogic::lm::vnf":    http://172.21.6.152/sandvine/lm_vnf/vnfd.yaml
   "packetlogic::lm::vnfc":    http://172.21.6.152/sandvine/lm_vnf/vnfc.yaml
   "packetlogic::pic::vnf":    http://172.21.6.152/sandvine/pic_vnf/vnfd.yaml
   "packetlogic::pic::vnfc":    http://172.21.6.152/sandvine/pic_vnf/vnfc.yaml
   "packetlogic::pre_group::ns":    http://172.21.6.152/sandvine/pre_group_ns/nsd.yaml
   "packetlogic::pre_group::balancer":    http://172.21.6.152/sandvine/pre_group_ns/balancer.yaml
   "packetlogic::pre::vnf":    http://172.21.6.152/sandvine/pre_vnf/vnfd.yaml
   "packetlogic::pre::vnfc":    http://172.21.6.152/sandvine/pre_vnf/vnfc.yaml
   "packetlogic::pre::channel_ports":    http://172.21.6.152/sandvine/pre_vnf/channel_ports.yaml
   "packetlogic::pre::channel_port":    http://172.21.6.152/sandvine/pre_vnf/channel_port.yaml
   "packetlogic::pre::vnf_indexed":    http://172.21.6.152/sandvine/pre_vnf/vnfd_indexed.yaml
   "packetlogic::pre::vnf_contrail":    http://172.21.6.152/sandvine/pre_vnf/vnfd_contrail.yamlpacketlogic::psm::vnf
   "packetlogic::psm::vnfc":    http://172.21.6.152/sandvine/psm_vnf/vnfc.yaml
   "packetlogic::channel_networks::channel":    http://172.21.6.152/sandvine/channel_networks_ns/channel.yaml
   "packetlogic::channel_networks::ns":    http://172.21.6.152/sandvine/channel_networks_ns/nsd.yaml
   "packetlogic::contrail_networks::channel":    http://172.21.6.152/sandvine/contrail_networks_ns/contrail_channel.yaml
   "packetlogic::contrail_networks::ns":    http://172.21.6.152/sandvine/contrail_networks_ns/nsd.yaml
   "packetlogic::lm::vnf":    http://172.21.6.152/sandvine/lm_vnf/vnfd.yaml
   "packetlogic::lm::vnfc":    http://172.21.6.152/sandvine/lm_vnf/vnfc.yaml
   "packetlogic::pic::vnf":    http://172.21.6.152/sandvine/pic_vnf/vnfd.yaml
   "packetlogic::pic::vnfc":    http://172.21.6.152/sandvine/pic_vnf/vnfc.yaml
   "packetlogic::pre_group::ns":    http://172.21.6.152/sandvine/pre_group_ns/nsd.yaml
   "packetlogic::pre_group::balancer":    http://172.21.6.152/sandvine/pre_group_ns/balancer.yaml
   "packetlogic::pre::vnf":    http://172.21.6.152/sandvine/pre_vnf/vnfd.yaml
   "packetlogic::pre::vnfc":    http://172.21.6.152/sandvine/pre_vnf/vnfc.yaml
   "packetlogic::pre::channel_ports":    http://172.21.6.152/sandvine/pre_vnf/channel_ports.yaml
   "packetlogic::pre::channel_port":    http://172.21.6.152/sandvine/pre_vnf/channel_port.yaml
   "packetlogic::pre::vnf_indexed":    http://172.21.6.152/sandvine/pre_vnf/vnfd_indexed.yaml
   "packetlogic::pre::vnf_contrail":    http://172.21.6.152/sandvine/pre_vnf/vnfd_contrail.yamlpacketlogic::psm::vnf
   "packetlogic::psm::vnfc":    http://172.21.6.152/sandvine/psm_vnf/vnfc.yaml
   "packetlogic::standard_networks::ns":    http://172.21.6.152/sandvine/standard_networks_ns/nsd.yaml
   "packetlogic::channel_networks::channel":    http://172.21.6.152/sandvine/channel_networks_ns/channel.yaml
   "packetlogic::channel_networks::ns":    http://172.21.6.152/sandvine/channel_networks_ns/nsd.yaml
   "packetlogic::contrail_networks::channel":    http://172.21.6.152/sandvine/contrail_networks_ns/contrail_channel.yaml
   "packetlogic::contrail_networks::ns":    http://172.21.6.152/sandvine/contrail_networks_ns/nsd.yaml
   "packetlogic::lm::vnf":    http://172.21.6.152/sandvine/lm_vnf/vnfd.yaml
   "packetlogic::lm::vnfc":    http://172.21.6.152/sandvine/lm_vnf/vnfc.yaml
   "packetlogic::pic::vnf":    http://172.21.6.152/sandvine/pic_vnf/vnfd.yaml
   "packetlogic::pic::vnfc":    http://172.21.6.152/sandvine/pic_vnf/vnfc.yaml
   "packetlogic::pre_group::ns":    http://172.21.6.152/sandvine/pre_group_ns/nsd.yaml
   "packetlogic::pre_group::balancer":    http://172.21.6.152/sandvine/pre_group_ns/balancer.yaml
   "packetlogic::pre::vnf":    http://172.21.6.152/sandvine/pre_vnf/vnfd.yaml
   "packetlogic::pre::vnfc":    http://172.21.6.152/sandvine/pre_vnf/vnfc.yaml
   "packetlogic::pre::channel_ports":    http://172.21.6.152/sandvine/pre_vnf/channel_ports.yaml
   "packetlogic::pre::channel_port":    http://172.21.6.152/sandvine/pre_vnf/channel_port.yaml
   "packetlogic::pre::vnf_indexed":    http://172.21.6.152/sandvine/pre_vnf/vnfd_indexed.yaml
   "packetlogic::pre::vnf_contrail":    http://172.21.6.152/sandvine/pre_vnf/vnfd_contrail.yamlpacketlogic::psm::vnf
   "packetlogic::psm::vnfc":    http://172.21.6.152/sandvine/psm_vnf/vnfc.yaml
   "packetlogic::standard_networks::ns":    http://172.21.6.152/sandvine/standard_networks_ns/nsd.yaml
   "packetlogic::standard_networks::ns":    http://172.21.6.152/sandvine/standard_networks_ns/nsd.yaml