"packetlogic::channel_networks::channel":    https://raw.githubusercontent.com/psergienko/heat/pl-vio/channel_networks_ns/channel.yaml
"packetlogic::channel_networks::ns":    https://raw.githubusercontent.com/psergienko/heat/pl-vio/channel_networks_ns/nsd.yaml
"packetlogic::pre::vnf":    https://raw.githubusercontent.com/psergienko/heat/pl-vio/pre_vnf/vnfd.yaml
"packetlogic::pre::vnfc":    https://raw.githubusercontent.com/psergienko/heat/pl-vio/pre_vnf/vnfc.yaml
"packetlogic::pre::channel_ports":    https://raw.githubusercontent.com/psergienko/heat/pl-vio/pre_vnf/channel_ports.yaml
"packetlogic::pre::channel_port":    https://raw.githubusercontent.com/psergienko/heat/pl-vio/pre_vnf/channel_port.yaml
"packetlogic::pre::vnf_indexed":    https://raw.githubusercontent.com/psergienko/heat/pl-vio/pre_vnf/vnfd_indexed.yaml
"packetlogic::pre::vnf_contrail":    https://raw.githubusercontent.com/psergienko/heat/pl-vio/pre_vnf/vnfd_contrail.yaml
"packetlogic::pre_scaling::ns":    https://raw.githubusercontent.com/psergienko/heat/pl-vio/pre_vnf/pre_scaling_ns.yamlpacketlogic::lm::vnf
"packetlogic::lm::vnfc":    https://raw.githubusercontent.com/psergienko/heat/pl-vio/lm_vnf/vnfc.yaml
"packetlogic::pre_group::ns":    https://raw.githubusercontent.com/psergienko/heat/pl-vio/pre_group_ns/nsd.yaml
"packetlogic::pre_group::balancer":    https://raw.githubusercontent.com/psergienko/heat/pl-vio/pre_group_ns/balancer.yaml
"packetlogic::pre::vnf":    https://raw.githubusercontent.com/psergienko/heat/pl-vio/pre_vnf/vnfd.yaml
"packetlogic::pre::vnfc":    https://raw.githubusercontent.com/psergienko/heat/pl-vio/pre_vnf/vnfc.yaml
"packetlogic::pre::channel_ports":    https://raw.githubusercontent.com/psergienko/heat/pl-vio/pre_vnf/channel_ports.yaml
"packetlogic::pre::channel_port":    https://raw.githubusercontent.com/psergienko/heat/pl-vio/pre_vnf/channel_port.yaml
"packetlogic::pre::vnf_indexed":    https://raw.githubusercontent.com/psergienko/heat/pl-vio/pre_vnf/vnfd_indexed.yaml
"packetlogic::channel_networks::channel":    https://raw.githubusercontent.com/psergienko/heat/pl-vio/channel_networks_ns/channel.yaml
"packetlogic::channel_networks::ns":    https://raw.githubusercontent.com/psergienko/heat/pl-vio/channel_networks_ns/nsd.yaml
"packetlogic::lm::vnf":    https://raw.githubusercontent.com/psergienko/heat/pl-vio/lm_vnf/vnfd.yaml
"packetlogic::lm::vnfc":    https://raw.githubusercontent.com/psergienko/heat/pl-vio/lm_vnf/vnfc.yaml
"packetlogic::pre_group::ns":    https://raw.githubusercontent.com/psergienko/heat/pl-vio/pre_group_ns/nsd.yaml
"packetlogic::pre_group::balancer":    https://raw.githubusercontent.com/psergienko/heat/pl-vio/pre_group_ns/balancer.yaml
"packetlogic::pre::vnf":    https://raw.githubusercontent.com/psergienko/heat/pl-vio/pre_vnf/vnfd.yaml
"packetlogic::pre::vnfc":    https://raw.githubusercontent.com/psergienko/heat/pl-vio/pre_vnf/vnfc.yaml
"packetlogic::pre::channel_ports":    https://raw.githubusercontent.com/psergienko/heat/pl-vio/pre_vnf/channel_ports.yaml
"packetlogic::pre::channel_port":    https://raw.githubusercontent.com/psergienko/heat/pl-vio/pre_vnf/channel_port.yaml
"packetlogic::pre::vnf_indexed":    https://raw.githubusercontent.com/psergienko/heat/pl-vio/pre_vnf/vnfd_indexed.yaml
"packetlogic::standard_networks::ns":    https://raw.githubusercontent.com/psergienko/heat/pl-vio/standard_networks_ns/nsd.yaml
